# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.TextField(help_text='The identifier for this challenge')),
                ('response', models.TextField(help_text='The response expected for this challenge')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Updated Timestamp')),
            ],
            options={
                'verbose_name': 'ACME Challenge',
                'verbose_name_plural': 'ACME Challenges',
            },
        ),
    ]
