# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsencrypt', '0003_make_challenge_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmechallenge',
            name='challenge',
            field=models.CharField(help_text='The identifier for this challenge', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='acmechallenge',
            name='response',
            field=models.CharField(help_text='The response expected for this challenge', max_length=255),
        ),
    ]
