# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsencrypt', '0003_make_challenge_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acmechallenge',
            name='created_ts',
        ),
        migrations.RemoveField(
            model_name='acmechallenge',
            name='updated_ts',
        ),
        migrations.AlterField(
            model_name='acmechallenge',
            name='challenge',
            field=models.CharField(
                help_text='The identifier for this challenge', max_length=255,
                unique=True),
        ),
        migrations.AlterField(
            model_name='acmechallenge',
            name='response',
            field=models.CharField(
                help_text='The response expected for this challenge',
                max_length=255),
        ),
    ]
